### ISSUE TITLE
Decide which field unit to pursue

### ISSUE THREAD

**Issue by ChadTeitsma** [Passageway/PassagewayFieldUnit#16]
CHIP, Pi, PiZero, or an Arduino option

**Comment by JaxonWright** [comment]
CHIP seems ideal, because it has an OS, Python Interpreter, WiFi, Bluetooth, and storage pre-installed. This was the general consensus between Tim, Zack, Chad and I.

**Comment by JaxonWright** [comment]
We have decided to use CHIP
