### ISSUE TITLE
Beam2 break from on object uses Beam1 break time from a different object for threshold 

### ISSUE THREAD

**Issue by zpattdev** [Passageway/PassagewayFieldUnit#29]
Object1 breaks Beam1 one and enters between beams.
Object2 breaks Beam1 and enters between beams.
Object1 breaks Beam2 and uses the time from Object2 to determine threshold.
Object2 breaks Beam2 and uses the time from Object2 to determine threshold.

The third line results in a lower threshold than expect.

Possible solutions (needs second opinion):
This problem may be solved by the solution for the issue "Records Really Small Objects."

A break count for each beam can be added that starts at zero and increments (with curr += curr % 10000 + 1 to keep below 10000) when that beam is broken. The break count of both beams should match, otherwise the beam is trying to compare to the entrance of another object.

**Comment by ChadTeitsma** [comment]
Fixed with the .5 second threshold determining that one beam cannot be broken more than once in a .5 second time window.
