### ISSUE TITLE
Finalize the Funding Request

### ISSUE THREAD

**Issue by JaxonWright** [Passageway/PassagewayFieldUnit#6]

**Comment by ChadTeitsma** [comment]
This includes identifying all of the locations and all of the hardware that we will need to use for each unit

**Comment by TimJung** [comment]
10.04 Funding request submitted for approval to Hans. Still needs approval from Leidig before card is completed.

**Comment by ChadTeitsma** [comment]
Received feedback from Hans. Tim is going to make changes and resubmit.
